const VERSION = '4.0.0-beta.1';
const LS = 'bencao:public-beta';

const herb = (x) => ({
  heroPos: '50% 50%',
  note: '影像用于本草镜视觉观察与体验，不替代植物学鉴定、药材质量鉴别或医疗建议。',
  ...x,
});

const HERBS = [
  herb({id:'bc001',no:'BC.001',name:'陈皮',pinyin:'CHÉN PÍ',latin:'Citri Reticulatae Pericarpium',plant:'Citrus reticulata Blanco',part:'干燥成熟果皮',color:'#A87546',hero:'./images/bc001-hero-vf1.webp',heroPos:'56% 48%',images:['./images/bc001-hero-vf1.webp','./images/bc001-02-fresh-peel.jpg','./images/bc001-03-dried-material.jpg','./images/bc001-atlas-outer.jpg','./images/bc001-atlas-inner.jpg','./images/bc001-atlas-edge.jpg','./images/bc001-atlas-section.jpg'],intro:'从果实到干燥果皮，颜色、卷曲、内外表面与油室一起构成陈皮的材料感。'}),
  herb({id:'bc002',no:'BC.002',name:'薄荷',pinyin:'BÒ HÉ',latin:'Menthae Haplocalycis Herba',plant:'Mentha haplocalyx Briq.',part:'干燥地上部分',color:'#71836B',hero:'./images/bc002-hero-vf1.webp',images:['./images/bc002-hero-vf1.webp','./images/bc002-detail-01-vu1.jpg','./images/bc002-detail-02-vu1.jpg','./images/bc002-detail-03-vu1.jpg','./images/bc002-detail-04-vu1.jpg','./images/bc002-detail-05-vu1.jpg'],intro:'叶脉、锯齿、四棱茎与花序，让“清凉”之外的薄荷结构变得可见。'}),
  herb({id:'bc003',no:'BC.003',name:'枸杞',pinyin:'GǑU QǏ',latin:'Lycii Fructus',plant:'Lycium barbarum L.',part:'干燥成熟果实',color:'#A55343',hero:'./images/bc003-hero-vf1.webp',images:['./images/bc003-hero-vf1.webp','./images/bc003-detail-01-vu1.jpg','./images/bc003-detail-02-vu1.jpg','./images/bc003-detail-03-vu1.jpg','./images/bc003-detail-04-vu1.jpg','./images/bc003-detail-05-vu1.jpg'],intro:'把“一把红色”拆成单颗之后，皱纹、轮廓、果柄痕与个体差异开始出现。'}),
  herb({id:'bc004',no:'BC.004',name:'桂花',pinyin:'GUÌ HUĀ',latin:'Osmanthus fragrans',plant:'Osmanthus fragrans (Thunb.) Lour.',part:'花',color:'#C49A4C',hero:'./images/bc004-hero-vf1.webp',images:['./images/bc004-hero-vf1.webp','./images/bc004-detail-01-vu1.jpg','./images/bc004-detail-02-vu1.jpg','./images/bc004-detail-03-vu1.jpg','./images/bc004-detail-04-vu1.jpg','./images/bc004-detail-05-vu1.jpg'],intro:'小尺度的花、花簇与干燥状态，需要靠近之后才能看到真正的结构层次。'}),
  herb({id:'bc005',no:'BC.005',name:'菊花',pinyin:'JÚ HUĀ',latin:'Chrysanthemi Flos',plant:'Chrysanthemum morifolium Ramat.',part:'干燥头状花序',color:'#B79A5A',hero:'./images/bc005-hero-vf1.webp',images:['./images/bc005-hero-vf1.webp','./images/bc005-detail-01-vu1.jpg','./images/bc005-detail-02-vu1.jpg','./images/bc005-detail-03-vu1.jpg','./images/bc005-detail-04-vu1.jpg','./images/bc005-detail-05-vu1.jpg'],intro:'先看整朵，再看花心、外围花瓣与基部。层次往往比颜色更重要。'}),
  herb({id:'bc006',no:'BC.006',name:'紫苏',pinyin:'ZǏ SŪ',latin:'Perillae Folium',plant:'Perilla frutescens (L.) Britt.',part:'干燥叶（或带嫩枝）',color:'#74586C',hero:'./images/bc006-hero-vf1.webp',images:['./images/bc006-hero-vf1.webp','./images/bc006-detail-01-vu1.jpg','./images/bc006-detail-02-vu1.jpg','./images/bc006-detail-03-vu1.jpg','./images/bc006-detail-04-vu1.jpg','./images/bc006-detail-05-vu1.jpg'],intro:'叶脉、锯齿、上下表面与卷曲共同建立紫苏叶的材料性格。'}),
  herb({id:'bc041',no:'BC.041',name:'木瓜',pinyin:'MÙ GUĀ',latin:'Chaenomelis Fructus',plant:'Chaenomeles speciosa',part:'干燥近成熟果实',color:'#A4774B',hero:'./images/bc041-mugua-hero-v1.avif',images:['./images/bc041-mugua-hero-v1.avif','./images/bc041-mugua-specimen-v1.avif','./images/bc041-mugua-detail-01-v1.avif','./images/bc041-mugua-detail-02-v1.avif','./images/bc041-mugua-detail-03-v1.avif','./images/bc041-mugua-detail-04-v1.avif','./images/bc041-mugua-detail-05-v1.avif'],intro:'果实、切面、种腔与干燥纤维被放到同一套摄影语言里，形成完整材料档案。'}),
  herb({id:'bc042',no:'BC.042',name:'罗汉果',pinyin:'LUÓ HÀN GUǑ',latin:'Siraitiae Fructus',plant:'Siraitia grosvenorii',part:'干燥果实',color:'#8D6848',hero:'./images/bc042-luohanguo-hero-v1.avif',images:['./images/bc042-luohanguo-hero-v1.avif','./images/bc042-luohanguo-specimen-v1.avif','./images/bc042-luohanguo-detail-01-v1.avif','./images/bc042-luohanguo-detail-02-v1.avif','./images/bc042-luohanguo-detail-03-v1.avif','./images/bc042-luohanguo-detail-04-v1.avif','./images/bc042-luohanguo-detail-05-v1.avif'],intro:'完整果实与破壳后的纤维、种子和内部腔室形成强烈的内外对照。'}),
  herb({id:'bc043',no:'BC.043',name:'桑椹',pinyin:'SĀNG SHÈN',latin:'Mori Fructus',plant:'Morus alba L.',part:'干燥果穗',color:'#604A50',hero:'./images/bc043-sangshen-hero-v1.avif',images:['./images/bc043-sangshen-hero-v1.avif','./images/bc043-sangshen-specimen-v1.avif','./images/bc043-sangshen-detail-01-v1.avif','./images/bc043-sangshen-detail-02-v1.avif','./images/bc043-sangshen-detail-03-v1.avif','./images/bc043-sangshen-detail-04-v1.avif','./images/bc043-sangshen-detail-05-v1.avif'],intro:'干燥果穗的深色、颗粒、皱缩和破开后的内部组织，构成细密而复杂的表面。'}),
  herb({id:'bc044',no:'BC.044',name:'酸枣仁',pinyin:'SUĀN ZǍO RÉN',latin:'Ziziphi Spinosae Semen',plant:'Ziziphus jujuba var. spinosa',part:'干燥成熟种子',color:'#805B4B',hero:'./images/bc044-suanzaoren-hero-v1.avif',images:['./images/bc044-suanzaoren-hero-v1.avif','./images/bc044-suanzaoren-specimen-v1.avif','./images/bc044-suanzaoren-detail-01-v1.avif','./images/bc044-suanzaoren-detail-02-v1.avif','./images/bc044-suanzaoren-detail-03-v1.avif','./images/bc044-suanzaoren-detail-04-v1.avif','./images/bc044-suanzaoren-detail-05-v1.avif'],intro:'种皮色泽、形状、边缘和内部结构被拆开观察；这一组仍建议后续继续做药材形态 QC。'}),
  herb({id:'bc045',no:'BC.045',name:'桃仁',pinyin:'TÁO RÉN',latin:'Persicae Semen',plant:'Prunus persica / Prunus davidiana',part:'干燥成熟种子',color:'#9B775A',hero:'./images/bc045-taoren-hero-v1.avif',images:['./images/bc045-taoren-hero-v1.avif','./images/bc045-taoren-specimen-v1.avif','./images/bc045-taoren-detail-01-v1.avif','./images/bc045-taoren-detail-02-v1.avif','./images/bc045-taoren-detail-03-v1.avif','./images/bc045-taoren-detail-04-v1.avif','./images/bc045-taoren-detail-05-v1.avif'],intro:'桃仁以种仁为主体；薄种皮、去皮种仁与断面共同建立视觉识别。'}),
  herb({published:false,id:'bc046',no:'BC.046',name:'车前子',pinyin:'CHĒ QIÁN ZǏ',latin:'Plantaginis Semen',plant:'Plantago asiatica / Plantago depressa',part:'干燥成熟种子',color:'#6E6658',hero:'./images/bc046-cheqianzi-hero-v1.avif',images:['./images/bc046-cheqianzi-hero-v1.avif','./images/bc046-cheqianzi-specimen-v1.avif','./images/bc046-cheqianzi-detail-01-v1.avif','./images/bc046-cheqianzi-detail-02-v1.avif','./images/bc046-cheqianzi-detail-03-v1.avif','./images/bc046-cheqianzi-detail-04-v1.avif','./images/bc046-cheqianzi-detail-05-v1.avif'],intro:'极小的种子需要通过整体、俯拍与微距逐层放大，才能看到色差、表面纹理与形态变化。'})
];

const LIVE_HERBS = HERBS.filter(h=>h.published!==false);
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seenKey=`${LS}:seen`; const getSeen=()=>{try{return new Set(JSON.parse(localStorage.getItem(seenKey)||'[]'))}catch{return new Set()}}; const saveSeen=s=>localStorage.setItem(seenKey,JSON.stringify([...s])); let seen=getSeen();
const image=(src,alt,eager=false)=>`<img src="${src}" alt="${esc(alt)}" ${eager?'loading="eager" fetchpriority="high"':'loading="lazy"'} decoding="async" onerror="this.closest('figure')?.classList.add('image-failed')">`;
function updateCount(){const count=LIVE_HERBS.filter(h=>seen.has(h.id)).length;$('#catalogueCount').textContent=`已浏览 ${count} / ${LIVE_HERBS.length}`;$('#catalogueTotal').textContent=`${LIVE_HERBS.length} 味可浏览本草`}
function renderCatalogue(){const grid=$('#herbGrid');grid.innerHTML=LIVE_HERBS.map(h=>`<button class="herb-card" type="button" data-herb="${h.id}" style="--herb-color:${h.color}"><div class="herb-card-figure"><img src="${h.hero}" alt="${esc(h.name)}" loading="lazy" decoding="async" style="object-position:${h.heroPos}"></div><div class="herb-card-body"><div class="herb-card-title"><span class="herb-card-id">${h.no}</span><h3>${h.name}</h3><span class="herb-card-pinyin">${h.pinyin}</span></div><div class="herb-card-latin">${h.latin}</div><div class="beta-card-meta"><span>${h.part}</span>${seen.has(h.id)?'<b>已浏览</b>':''}</div><div class="herb-card-link">查看图集 →</div></div></button>`).join('');$$('.herb-card',grid).forEach(btn=>btn.addEventListener('click',()=>openHerb(btn.dataset.herb)));updateCount()}
function galleryLabels(h){return h.images.length===7?['Hero','Specimen','Detail 01','Detail 02','Detail 03','Detail 04','Detail 05']:h.images.map((_,i)=>i===0?'Hero':`Study ${String(i).padStart(2,'0')}`)}
function renderDetail(h){const labels=galleryLabels(h),idx=LIVE_HERBS.findIndex(x=>x.id===h.id),prev=LIVE_HERBS[(idx-1+LIVE_HERBS.length)%LIVE_HERBS.length],next=LIVE_HERBS[(idx+1)%LIVE_HERBS.length];$('#detailView').innerHTML=`<section class="beta-detail" style="--herb-color:${h.color}"><div class="beta-detail-nav"><button type="button" data-go-catalogue>← 本草目录</button><span>PUBLIC BETA · ${VERSION}</span><button type="button" data-copy-link>复制当前链接</button></div><div class="beta-hero"><div class="beta-hero-copy"><p class="eyebrow">${h.no} / DIGITAL HERBARIUM</p><h1>${h.name}</h1><p class="beta-pinyin">${h.pinyin}</p><p class="latin">${h.latin}</p><div class="beta-taxonomy"><span>${h.plant}</span><span>${h.part}</span></div><p class="beta-intro">${h.intro}</p><button class="beta-seen" type="button" data-mark-seen>${seen.has(h.id)?'已浏览这味':'标记为已浏览'}</button></div><figure class="beta-hero-image">${image(h.hero,`${h.name} Hero`,true)}<figcaption>${h.no} · HERO</figcaption></figure></div><div class="beta-gallery-head"><div><p class="eyebrow">FORMAL VISUAL ASSETS</p><h2>材料图集</h2></div><p>${h.images.length} 张 · 点击可放大</p></div><div class="beta-gallery">${h.images.map((src,i)=>`<figure data-lightbox="${i}">${image(src,`${h.name} ${labels[i]}`)}<figcaption><span>${labels[i]}</span><small>${h.no}</small></figcaption></figure>`).join('')}</div><aside class="beta-disclaimer"><strong>测试版说明</strong><p>${h.note}</p></aside><div class="beta-next"><button type="button" data-herb-nav="${prev.id}">← ${prev.no} ${prev.name}</button><button type="button" data-herb-nav="${next.id}">${next.no} ${next.name} →</button></div></section>`;$$('[data-go-catalogue]',$('#detailView')).forEach(b=>b.addEventListener('click',goCatalogue));$$('[data-herb-nav]',$('#detailView')).forEach(b=>b.addEventListener('click',()=>openHerb(b.dataset.herbNav)));$('[data-mark-seen]',$('#detailView')).addEventListener('click',e=>{seen.add(h.id);saveSeen(seen);e.currentTarget.textContent='已浏览这味';renderCatalogue()});$('[data-copy-link]',$('#detailView')).addEventListener('click',async e=>{try{await navigator.clipboard.writeText(location.href);e.currentTarget.textContent='链接已复制';setTimeout(()=>e.currentTarget.textContent='复制当前链接',1400)}catch{}});$$('[data-lightbox]',$('#detailView')).forEach(f=>f.addEventListener('click',()=>openLightbox(h,Number(f.dataset.lightbox))))}
function openHerb(id,push=true){const h=LIVE_HERBS.find(x=>x.id===id)||LIVE_HERBS[0];seen.add(h.id);saveSeen(seen);renderDetail(h);renderCatalogue();$('#catalogueView').hidden=true;$('#detailView').hidden=false;document.body.classList.add('in-detail');if(push)history.pushState({herb:h.id},'',`#${h.id}`);window.scrollTo({top:0,behavior:'instant'})}
function goCatalogue(push=true){$('#catalogueView').hidden=false;$('#detailView').hidden=true;document.body.classList.remove('in-detail');if(push)history.pushState({},'',location.pathname+location.search);renderCatalogue();window.scrollTo({top:0,behavior:'instant'})}
function openLightbox(h,start){const labels=galleryLabels(h),dlg=$('#imageDialog');let i=start;const draw=()=>{$('#lightboxImage').src=h.images[i];$('#lightboxImage').alt=`${h.name} ${labels[i]}`;$('#lightboxCaption').textContent=`${h.no} · ${h.name} · ${labels[i]} · ${i+1}/${h.images.length}`};draw();dlg.showModal();dlg.querySelector('[data-prev-image]').onclick=()=>{i=(i-1+h.images.length)%h.images.length;draw()};dlg.querySelector('[data-next-image]').onclick=()=>{i=(i+1)%h.images.length;draw()}}
function bindGlobal(){$$('[data-go-catalogue]').forEach(b=>b.addEventListener('click',()=>goCatalogue()));$('[data-open-about]').addEventListener('click',()=>$('#aboutDialog').showModal());$$('[data-dialog-close]').forEach(b=>b.addEventListener('click',()=>b.closest('dialog').close()));$('#imageDialog').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()});window.addEventListener('popstate',()=>{const id=location.hash.replace('#','');if(LIVE_HERBS.some(h=>h.id===id))openHerb(id,false);else goCatalogue(false)})}
renderCatalogue();bindGlobal();const initial=location.hash.replace('#','');if(LIVE_HERBS.some(h=>h.id===initial))openHerb(initial,false);
