const VERSION='4.0.0';
const LS='bencao:public-beta';
const herb=x=>({heroPos:'50% 50%',note:'影像用于本草镜视觉观察与体验，不替代植物学鉴定、药材质量鉴别或医疗建议。 ',...x});
const F=[
herb({id:'bc001',no:'BC.001',name:'陈皮',pinyin:'CHÉN PÍ',latin:'Citri Reticulatae Pericarpium',plant:'Citrus reticulata Blanco',part:'干燥成熟果皮',color:'#A87546',hero:'./images/bc001-hero-vf1.webp',heroPos:'56% 48%',images:['./images/bc001-hero-vf1.webp','./images/bc001-02-fresh-peel.jpg','./images/bc001-03-dried-material.jpg','./images/bc001-atlas-outer.jpg','./images/bc001-atlas-inner.jpg','./images/bc001-atlas-edge.jpg','./images/bc001-atlas-section.jpg'],intro:'从果实到干燥果皮，颜色、卷曲、内外表面与油室一起构成陈皮的材料感。'}),
herb({id:'bc002',no:'BC.002',name:'薄荷',pinyin:'BÒ HÉ',latin:'Menthae Haplocalycis Herba',plant:'Mentha haplocalyx Briq.',part:'干燥地上部分',color:'#71836B',hero:'./images/bc002-hero-vf1.webp',images:['./images/bc002-hero-vf1.webp','./images/bc002-atlas-plate-vu1.jpg','./images/bc002-detail-01-vu1.jpg','./images/bc002-detail-02-vu1.jpg','./images/bc002-detail-03-vu1.jpg','./images/bc002-detail-04-vu1.jpg','./images/bc002-detail-05-vu1.jpg'],intro:'叶脉、锯齿、四棱茎与花序，让“清凉”之外的薄荷结构变得可见。'}),
herb({id:'bc003',no:'BC.003',name:'枸杞',pinyin:'GǑU QǏ',latin:'Lycii Fructus',plant:'Lycium barbarum L.',part:'干燥成熟果实',color:'#A55343',hero:'./images/bc003-hero-vf1.webp',images:['./images/bc003-hero-vf1.webp','./images/bc003-atlas-plate-vu1.jpg','./images/bc003-detail-01-vu1.jpg','./images/bc003-detail-02-vu1.jpg','./images/bc003-detail-03-vu1.jpg','./images/bc003-detail-04-vu1.jpg','./images/bc003-detail-05-vu1.jpg'],intro:'把“一把红色”拆成单颗之后，皱纹、轮廓、果柄痕与个体差异开始出现。'}),
herb({id:'bc004',no:'BC.004',name:'桂花',pinyin:'GUÌ HUĀ',latin:'Osmanthus fragrans',plant:'Osmanthus fragrans (Thunb.) Lour.',part:'花',color:'#C49A4C',hero:'./images/bc004-hero-vf1.webp',images:['./images/bc004-hero-vf1.webp','./images/bc004-atlas-plate-vu1.jpg','./images/bc004-detail-01-vu1.jpg','./images/bc004-detail-02-vu1.jpg','./images/bc004-detail-03-vu1.jpg','./images/bc004-detail-04-vu1.jpg','./images/bc004-detail-05-vu1.jpg'],intro:'小尺度的花、花簇与干燥状态，需要靠近之后才能看到真正的结构层次。'}),
herb({id:'bc005',no:'BC.005',name:'菊花',pinyin:'JÚ HUĀ',latin:'Chrysanthemi Flos',plant:'Chrysanthemum morifolium Ramat.',part:'干燥头状花序',color:'#B79A5A',hero:'./images/bc005-hero-vf1.webp',images:['./images/bc005-hero-vf1.webp','./images/bc005-atlas-plate-vu1.jpg','./images/bc005-detail-01-vu1.jpg','./images/bc005-detail-02-vu1.jpg','./images/bc005-detail-03-vu1.jpg','./images/bc005-detail-04-vu1.jpg','./images/bc005-detail-05-vu1.jpg'],intro:'先看整朵，再看花心、外围花瓣与基部。层次往往比颜色更重要。'}),
herb({id:'bc006',no:'BC.006',name:'紫苏',pinyin:'ZǏ SŪ',latin:'Perillae Folium',plant:'Perilla frutescens (L.) Britt.',part:'干燥叶（或带嫩枝）',color:'#74586C',hero:'./images/bc006-hero-vf1.webp',images:['./images/bc006-hero-vf1.webp','./images/bc006-atlas-plate-vu1.jpg','./images/bc006-detail-01-vu1.jpg','./images/bc006-detail-02-vu1.jpg','./images/bc006-detail-03-vu1.jpg','./images/bc006-detail-04-vu1.jpg','./images/bc006-detail-05-vu1.jpg'],intro:'叶脉、锯齿、上下表面与卷曲共同建立紫苏叶的材料性格。'})
];
const P=[
['007','金银花','Lonicerae Japonicae Flos','干燥花蕾或初开的花','#9A8A63'],['008','山楂','Crataegi Fructus','干燥成熟果实','#9A644B'],['009','甘草','Glycyrrhizae Radix et Rhizoma','干燥根和根茎','#8A6A49'],['010','当归','Angelicae Sinensis Radix','干燥根','#8A624E'],['011','黄芪','Astragali Radix','干燥根','#A18255'],['012','茯苓','Poria','干燥菌核','#8C8370'],['013','薏苡仁','Coicis Semen','干燥成熟种仁','#B5A27A'],['014','莲子','Nelumbinis Semen','干燥成熟种子','#9A8264'],['015','决明子','Cassiae Semen','干燥成熟种子','#806B50'],['016','大枣','Jujubae Fructus','干燥成熟果实','#9D5E4F'],['017','人参','Ginseng Radix et Rhizoma','干燥根和根茎','#9A7C55'],['018','丹参','Salviae Miltiorrhizae Radix et Rhizoma','干燥根和根茎','#8C5A4F'],['019','连翘','Forsythiae Fructus','干燥果实','#8C7051'],['020','麦冬','Ophiopogonis Radix','干燥块根','#A58B6C'],['021','五味子','Schisandrae Chinensis Fructus','干燥成熟果实','#7B5B50'],['022','百合','Lilii Bulbus','干燥肉质鳞叶','#B3A58B'],['023','肉桂','Cinnamomi Cortex','干燥树皮','#91684C'],['024','丁香','Caryophylli Flos','干燥花蕾','#6F5B4E'],['025','砂仁','Amomi Fructus','干燥成熟果实','#7B684E'],['026','厚朴','Magnoliae Officinalis Cortex','干燥干皮、根皮及枝皮','#806351'],['027','黄连','Coptidis Rhizoma','干燥根茎','#6F5D48'],['028','黄芩','Scutellariae Radix','干燥根','#7C654C'],['029','泽泻','Alismatis Rhizoma','干燥块茎','#8A7256'],['030','半夏','Pinelliae Rhizoma','干燥块茎','#786550'],['031','天麻','Gastrodiae Rhizoma','干燥块茎','#8B7359'],['032','牛膝','Achyranthis Bidentatae Radix','干燥根','#715A47'],['033','杜仲','Eucommiae Cortex','干燥树皮','#775E48'],['034','木香','Aucklandiae Radix','干燥根','#7E684F'],['035','鸡血藤','Spatholobi Caulis','干燥藤茎','#795D4E'],['036','苏木','Sappan Lignum','干燥心材','#755846'],['037','栀子','Gardeniae Fructus','干燥成熟果实','#9A704B'],['038','枳实','Aurantii Fructus Immaturus','干燥幼果','#7A5946'],['039','佛手','Citri Sarcodactylis Fructus','干燥果实','#9B7049'],['040','乌梅','Mume Fructus','干燥近成熟果实','#6F584B']
].map(([n,name,latin,part,color])=>herb({assetStatus:'pending',id:`bc${n}`,no:`BC.${n}`,name,pinyin:'',latin,plant:'',part,color,hero:null,images:[],intro:'该条目已进入公开测试目录；正式影像资产仍在补齐。当前页面用于验证目录结构、编号顺序与浏览路径。',note:'本条目的正式影像尚未提交到 GitHub 资产库；页面不会用其他药材图片代替。'}));

const LIVE_ASSET_SLUGS={"bc007":"jinyinhua","bc008":"shanzha","bc009":"gancao","bc010":"danggui","bc011":"huangqi","bc012":"fuling","bc013":"yiyiren","bc014":"lianzi","bc015":"juemingzi","bc016":"dazao","bc017":"renshen","bc018":"danshen","bc019":"lianqiao","bc020":"maidong","bc021":"wuweizi","bc022":"baihe","bc023":"rougui","bc024":"dingxiang","bc025":"sharen","bc026":"houpo","bc027":"huanglian","bc028":"huangqin","bc029":"zexie","bc030":"banxia","bc031":"tianma","bc032":"niuxi","bc033":"duzhong","bc034":"muxiang","bc035":"jixueteng","bc036":"sumu","bc037":"zhizi","bc038":"zhishi","bc039":"foshou","bc040":"wumei"};
P.forEach(h=>{const s=LIVE_ASSET_SLUGS[h.id];if(!s)return;h.assetStatus='formal_hd_asset';h.hero=`./images/${h.id}-${s}-hero-v1.webp`;h.images=[`./images/${h.id}-${s}-hero-v1.webp`,`./images/${h.id}-${s}-specimen-v1.webp`,...Array.from({length:5},(_,i)=>`./images/${h.id}-${s}-detail-0${i+1}-v1.webp`)];h.intro='本条目已接入 7 张高清材料观察图，从整体、标本视角到局部纹理连续浏览。';h.note='高清影像用于本草材料观察与产品体验，不替代植物学鉴定、药材质量鉴别或医疗建议。';});
const T=[
herb({id:'bc041',no:'BC.041',name:'木瓜',pinyin:'MÙ GUĀ',latin:'Chaenomelis Fructus',plant:'Chaenomeles speciosa',part:'干燥近成熟果实',color:'#A4774B',hero:'./images/bc041-mugua-hero-v1.avif',images:['./images/bc041-mugua-hero-v1.avif','./images/bc041-mugua-specimen-v1.avif','./images/bc041-mugua-detail-01-v1.avif','./images/bc041-mugua-detail-02-v1.avif','./images/bc041-mugua-detail-03-v1.avif','./images/bc041-mugua-detail-04-v1.avif','./images/bc041-mugua-detail-05-v1.avif'],intro:'果实、切面、种腔与干燥纤维被放到同一套摄影语言里，形成完整材料档案。'}),
herb({id:'bc042',no:'BC.042',name:'罗汉果',pinyin:'LUÓ HÀN GUǑ',latin:'Siraitiae Fructus',plant:'Siraitia grosvenorii',part:'干燥果实',color:'#8D6848',hero:'./images/bc042-luohanguo-hero-v1.avif',images:['./images/bc042-luohanguo-hero-v1.avif','./images/bc042-luohanguo-specimen-v1.avif','./images/bc042-luohanguo-detail-01-v1.avif','./images/bc042-luohanguo-detail-02-v1.avif','./images/bc042-luohanguo-detail-03-v1.avif','./images/bc042-luohanguo-detail-04-v1.avif','./images/bc042-luohanguo-detail-05-v1.avif'],intro:'完整果实与破壳后的纤维、种子和内部腔室形成强烈的内外对照。'}),
herb({id:'bc043',no:'BC.043',name:'桑椹',pinyin:'SĀNG SHÈN',latin:'Mori Fructus',plant:'Morus alba L.',part:'干燥果穗',color:'#604A50',hero:'./images/bc043-sangshen-hero-v1.avif',images:['./images/bc043-sangshen-hero-v1.avif','./images/bc043-sangshen-specimen-v1.avif','./images/bc043-sangshen-detail-01-v1.avif','./images/bc043-sangshen-detail-02-v1.avif','./images/bc043-sangshen-detail-03-v1.avif','./images/bc043-sangshen-detail-04-v1.avif','./images/bc043-sangshen-detail-05-v1.avif'],intro:'干燥果穗的深色、颗粒、皱缩和破开后的内部组织，构成细密而复杂的表面。'}),
herb({id:'bc044',no:'BC.044',name:'酸枣仁',pinyin:'SUĀN ZǍO RÉN',latin:'Ziziphi Spinosae Semen',plant:'Ziziphus jujuba var. spinosa',part:'干燥成熟种子',color:'#805B4B',hero:'./images/bc044-suanzaoren-hero-v1.avif',images:['./images/bc044-suanzaoren-hero-v1.avif','./images/bc044-suanzaoren-specimen-v1.avif','./images/bc044-suanzaoren-detail-01-v1.avif','./images/bc044-suanzaoren-detail-02-v1.avif','./images/bc044-suanzaoren-detail-03-v1.avif','./images/bc044-suanzaoren-detail-04-v1.avif','./images/bc044-suanzaoren-detail-05-v1.avif'],intro:'种皮色泽、形状、边缘和内部结构被拆开观察；这一组仍建议后续继续做药材形态 QC。'}),
herb({id:'bc045',no:'BC.045',name:'桃仁',pinyin:'TÁO RÉN',latin:'Persicae Semen',plant:'Prunus persica / Prunus davidiana',part:'干燥成熟种子',color:'#9B775A',hero:'./images/bc045-taoren-hero-v1.avif',images:['./images/bc045-taoren-hero-v1.avif','./images/bc045-taoren-specimen-v1.avif','./images/bc045-taoren-detail-01-v1.avif','./images/bc045-taoren-detail-02-v1.avif','./images/bc045-taoren-detail-03-v1.avif','./images/bc045-taoren-detail-04-v1.avif','./images/bc045-taoren-detail-05-v1.avif'],intro:'桃仁以种仁为主体；薄种皮、去皮种仁与断面共同建立视觉识别。'}),
herb({assetStatus:'formal_hd_asset',id:'bc046',no:'BC.046',name:'车前子',pinyin:'CHĒ QIÁN ZǏ',latin:'Plantaginis Semen',plant:'Plantago asiatica / Plantago depressa',part:'干燥成熟种子',color:'#6E6658',hero:'./images/bc046-cheqianzi-hero-v1.webp',images:['./images/bc046-cheqianzi-hero-v1.webp','./images/bc046-cheqianzi-specimen-v1.webp','./images/bc046-cheqianzi-detail-01-v1.webp','./images/bc046-cheqianzi-detail-02-v1.webp','./images/bc046-cheqianzi-detail-03-v1.webp','./images/bc046-cheqianzi-detail-04-v1.webp','./images/bc046-cheqianzi-detail-05-v1.webp'],intro:'车前子已接入 7 张高清图，展示整体、标本视角与局部细节。',note:'高清影像用于本草材料观察与产品体验，不替代药材质量鉴别或医疗建议。'})
];
// QA hold: these six sets have documented identity/medicinal-part or layout failures.
// Keep historical binaries for comparison; do not expose them as approved imagery.
const QC_HOLD_IDS=new Set(['bc041','bc042','bc043','bc044','bc045','bc046']);
T.forEach(h=>{if(!QC_HOLD_IDS.has(h.id))return;h.assetStatus='qc_hold';h.hero=null;h.images=[];h.intro='旧版影像在主题一致性或药材形态检查中未通过，现已撤下，正在重新核对和制作。';h.note='本条目的旧版图集未通过逐张验收，暂不对外展示。保留条目仅供浏览目录，不应凭此前图像进行药材识别。';});
// BC.007 source audit: all seven images derive from living flower/vine photos,
// not from documented dried medicinal buds; one source is only identified to genus.
P.forEach(h=>{if(h.id!=='bc007')return;h.assetStatus='qc_hold';h.hero=null;h.images=[];h.intro='金银花旧图集采用活体花朵及花枝摄影，与干燥金银花药材标本不符；旧图已撤下，正在逐张重新验收。';h.note='旧版 7 张均未通过药用部位/参考来源验收，其中部分参考照片未明确到忍冬这一药典基源。请勿使用旧图判断金银花药材形态。';});
const HERBS=[...F,...P,...T];
// 46 味的影像全部来自生成式流程，没有一张是实拍记录。按项目红线，AI 生成影像
// 必须对使用者可见标注，不能只写在仓库文档里。这里给全部条目挂上标记，
// 卡片、条目页主图、图集说明与灯箱都会显示徽标或 AI 字样。
const AI_TAG='AI 生成影像';
const AI_NOTE='本条目 7 张影像均为 AI 生成图像（BENCAO Visual Study 原型素材），不是实拍药材记录；部分以公开许可照片为参考源。影像用于材料观察与产品体验，不替代植物学鉴定、药材质量鉴别或医疗建议。每张影像的来源与署名见 credits.html。';
HERBS.forEach(h=>{h.ai=true;if(h.assetStatus!=='qc_hold')h.note=AI_NOTE});
const badge=h=>h.ai&&has(h)?`<span class="asset-tag-ai">${AI_TAG}</span>`:'';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=`${LS}:seen`;const read=()=>{try{return new Set(JSON.parse(localStorage.getItem(key)||'[]'))}catch{return new Set()}};const write=s=>localStorage.setItem(key,JSON.stringify([...s]));let seen=read();
const has=h=>Array.isArray(h.images)&&h.images.length>0;
const ph=(h,label)=>`<div class="beta-placeholder"><span>${h.no}</span><strong>${h.name}</strong><small>${label}</small></div>`;
const pic=(src,alt,eager=false)=>`<img src="${src}" alt="${esc(alt)}" ${eager?'loading="eager" fetchpriority="high"':'loading="lazy"'} decoding="async">`;
function updateCount(){const n=HERBS.filter(h=>seen.has(h.id)).length;$('#catalogueCount').textContent=`已浏览 ${n} / ${HERBS.length}`;$('#catalogueTotal').textContent=`${HERBS.length} 味可浏览本草`}
function renderCatalogue(){const g=$('#herbGrid');g.innerHTML=HERBS.map(h=>`<button class="herb-card" data-herb="${h.id}" style="--herb-color:${h.color}"><div class="herb-card-figure ${has(h)?'':'pending-figure'}">${has(h)?`<img src="${h.hero}" alt="${esc(h.name)}" loading="lazy" decoding="async" style="object-position:${h.heroPos}">`:ph(h,h.assetStatus==='qc_hold'?'影像复核中':h.assetStatus==='staged'?'高清图待入库':'正式影像待补')}${badge(h)}</div><div class="herb-card-body"><div class="herb-card-title"><span class="herb-card-id">${h.no}</span><h3>${h.name}</h3></div><div class="herb-card-latin">${h.latin}</div><div class="beta-card-meta"><span>${h.part}</span><b>${has(h)?(seen.has(h.id)?'已浏览':'正式影像'):h.assetStatus==='qc_hold'?'影像复核中':h.assetStatus==='staged'?'待入库':'影像待补'}</b></div><div class="herb-card-link">查看条目 →</div></div></button>`).join('');$$('[data-herb]',g).forEach(b=>b.onclick=()=>openHerb(b.dataset.herb));updateCount()}
const labels=['Hero','Specimen','Detail 01','Detail 02','Detail 03','Detail 04','Detail 05'];
function renderDetail(h){const i=HERBS.findIndex(x=>x.id===h.id),prev=HERBS[(i-1+HERBS.length)%HERBS.length],next=HERBS[(i+1)%HERBS.length];$('#detailView').innerHTML=`<section class="beta-detail" style="--herb-color:${h.color}"><div class="beta-detail-nav"><button data-go-catalogue>← 本草目录</button><span>PUBLIC BETA · ${VERSION}</span><button data-copy-link>复制当前链接</button></div><div class="beta-hero"><div class="beta-hero-copy"><p class="eyebrow">${h.no} / DIGITAL HERBARIUM</p><h1>${h.name}</h1>${h.pinyin?`<p class="beta-pinyin">${h.pinyin}</p>`:''}<p class="latin">${h.latin}</p><div class="beta-taxonomy">${h.plant?`<span>${h.plant}</span>`:''}<span>${h.part}</span></div><p class="beta-intro">${h.intro}</p><button class="beta-seen" data-mark-seen>${seen.has(h.id)?'已浏览这味':'标记为已浏览'}</button></div><figure class="beta-hero-image ${has(h)?'':'pending-figure'}">${has(h)?pic(h.hero,`${h.name} Hero`,true):ph(h,h.assetStatus==='qc_hold'?'影像复核中':'正式影像待补')}${badge(h)}<figcaption>${h.no} · ${has(h)?'HERO':'ASSET PENDING'}</figcaption></figure></div><div class="beta-gallery-head"><div><p class="eyebrow">${has(h)?'FORMAL VISUAL ASSETS':'ASSET SLOTS / PENDING'}</p><h2>材料图集</h2></div><p>${has(h)?`${h.images.length} 张 · 点击可放大`:'7 个正式资产位 · 待补'}</p></div><div class="beta-gallery ${has(h)?'':'pending-gallery'}">${has(h)?h.images.map((src,j)=>`<figure data-lightbox="${j}">${pic(src,`${h.name} ${labels[j]||`Study ${j}`}`)}<figcaption><span>${labels[j]||`Study ${j}`}</span><small>${h.no}${h.ai?' · AI':''}</small></figcaption></figure>`).join(''):labels.map(l=>`<figure>${ph(h,l)}<figcaption><span>${l}</span><small>待补</small></figcaption></figure>`).join('')}</div><aside class="beta-disclaimer"><strong>测试版说明</strong><p>${h.note}</p></aside><div class="beta-next"><button data-herb-nav="${prev.id}">← ${prev.no} ${prev.name}</button><button data-herb-nav="${next.id}">${next.no} ${next.name} →</button></div></section>`;$$('[data-go-catalogue]',$('#detailView')).forEach(b=>b.onclick=goCatalogue);$$('[data-herb-nav]',$('#detailView')).forEach(b=>b.onclick=()=>openHerb(b.dataset.herbNav));$('[data-mark-seen]',$('#detailView')).onclick=e=>{seen.add(h.id);write(seen);e.currentTarget.textContent='已浏览这味';renderCatalogue()};$('[data-copy-link]',$('#detailView')).onclick=async e=>{try{await navigator.clipboard.writeText(location.href);e.currentTarget.textContent='链接已复制';setTimeout(()=>e.currentTarget.textContent='复制当前链接',1200)}catch{}};$$('[data-lightbox]',$('#detailView')).forEach(f=>f.onclick=()=>openLightbox(h,+f.dataset.lightbox))}
function openHerb(id,push=true){const h=HERBS.find(x=>x.id===id)||HERBS[0];seen.add(h.id);write(seen);renderDetail(h);renderCatalogue();$('#catalogueView').hidden=true;$('#detailView').hidden=false;document.body.classList.add('in-detail');if(push)history.pushState({herb:h.id},'',`#${h.id}`);scrollTo({top:0,behavior:'instant'})}
function goCatalogue(push=true){$('#catalogueView').hidden=false;$('#detailView').hidden=true;document.body.classList.remove('in-detail');if(push)history.pushState({},'',location.pathname+location.search);renderCatalogue();scrollTo({top:0,behavior:'instant'})}
function openLightbox(h,start){if(!has(h))return;let i=start;const d=$('#imageDialog');const draw=()=>{$('#lightboxImage').src=h.images[i];$('#lightboxImage').alt=`${h.name} ${labels[i]||''}`;$('#lightboxCaption').textContent=`${h.no} · ${h.name} · ${labels[i]||''} · ${i+1}/${h.images.length}${h.ai?' · AI 生成影像':''}`};draw();d.showModal();d.querySelector('[data-prev-image]').onclick=()=>{i=(i-1+h.images.length)%h.images.length;draw()};d.querySelector('[data-next-image]').onclick=()=>{i=(i+1)%h.images.length;draw()}}
$$('[data-go-catalogue]').forEach(b=>b.onclick=()=>goCatalogue());$('[data-open-about]').onclick=()=>$('#aboutDialog').showModal();$$('[data-dialog-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#imageDialog').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.close()};addEventListener('popstate',()=>{const id=location.hash.slice(1);HERBS.some(h=>h.id===id)?openHerb(id,false):goCatalogue(false)});renderCatalogue();const initial=location.hash.slice(1);if(HERBS.some(h=>h.id===initial))openHerb(initial,false);
